// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  aiPlayerId: __t.i32().name("ai_player_id"),
  cycleAt: __t.i64().name("cycle_at"),
  reasoningText: __t.string().name("reasoning_text"),
  actionsTaken: __t.string().name("actions_taken"),
});
