// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  aiPlayerId: __t.i32().primaryKey().name("ai_player_id"),
  cycleStatus: __t.string().name("cycle_status"),
  lastCycleAt: __t.i64().name("last_cycle_at"),
  nextCycleAt: __t.i64().name("next_cycle_at"),
});
