// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  aiPlayerId: __t.i32().name("ai_player_id"),
  targetPlayerId: __t.i32().name("target_player_id"),
  trustScore: __t.i32().name("trust_score"),
  messagesEvaluated: __t.i32().name("messages_evaluated"),
  truthsConfirmed: __t.i32().name("truths_confirmed"),
  liesCaught: __t.i32().name("lies_caught"),
  lastUpdated: __t.i64().name("last_updated"),
});
