// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  timestamp: __t.i64(),
  senderId: __t.i32().name("sender_id"),
  recipientId: __t.i32().name("recipient_id"),
  messageText: __t.string().name("message_text"),
  territoryId: __t.i32().name("territory_id"),
});
