// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.i32().primaryKey().name("player_id"),
  playerName: __t.string().name("player_name"),
  color: __t.string(),
  actionPoints: __t.i32().name("action_points"),
  lastRegenAt: __t.i64().name("last_regen_at"),
});
