// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  createdAt: __t.i64().name("created_at"),
  notification: __t.string(),
  priority: __t.string(),
  territoryId: __t.i32().name("territory_id"),
  playerId: __t.i32().name("player_id"),
  dismissed: __t.bool(),
});
