// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AiCycleSchedule = __t.object("AiCycleSchedule", {
  scheduledId: __t.u64(),
  aiPlayerId: __t.i32(),
  scheduledAt: __t.scheduleAt(),
});
export type AiCycleSchedule = __Infer<typeof AiCycleSchedule>;

export const AiReasoningLog = __t.object("AiReasoningLog", {
  id: __t.u64(),
  aiPlayerId: __t.i32(),
  cycleAt: __t.i64(),
  reasoningText: __t.string(),
  actionsTaken: __t.string(),
});
export type AiReasoningLog = __Infer<typeof AiReasoningLog>;

export const AiState = __t.object("AiState", {
  aiPlayerId: __t.i32(),
  cycleStatus: __t.string(),
  lastCycleAt: __t.i64(),
  nextCycleAt: __t.i64(),
});
export type AiState = __Infer<typeof AiState>;

export const Covert = __t.object("Covert", {
  territoryId: __t.i32(),
  ownerId: __t.i32(),
  agentCount: __t.i32(),
});
export type Covert = __Infer<typeof Covert>;

export const Cultural = __t.object("Cultural", {
  territoryId: __t.i32(),
  ownerId: __t.i32(),
  influencePct: __t.i32(),
});
export type Cultural = __Infer<typeof Cultural>;

export const CulturalTimer = __t.object("CulturalTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CulturalTimer = __Infer<typeof CulturalTimer>;

export const Economic = __t.object("Economic", {
  territoryId: __t.i32(),
  ownerId: __t.i32(),
  capital: __t.i32(),
});
export type Economic = __Infer<typeof Economic>;

export const GameState = __t.object("GameState", {
  key: __t.string(),
  value: __t.string(),
});
export type GameState = __Infer<typeof GameState>;

export const IntelResult = __t.object("IntelResult", {
  status: __t.string(),
  intelText: __t.string(),
  aiPlayerName: __t.string(),
  cycleTimestamp: __t.i64(),
  territoriesReferenced: __t.array(__t.i32()),
});
export type IntelResult = __Infer<typeof IntelResult>;

export const Military = __t.object("Military", {
  territoryId: __t.i32(),
  ownerId: __t.i32(),
  troopCount: __t.i32(),
});
export type Military = __Infer<typeof Military>;

export const ModuleConfig = __t.object("ModuleConfig", {
  key: __t.string(),
  value: __t.string(),
});
export type ModuleConfig = __Infer<typeof ModuleConfig>;

export const Player = __t.object("Player", {
  playerId: __t.i32(),
  playerName: __t.string(),
  color: __t.string(),
  actionPoints: __t.i32(),
  lastRegenAt: __t.i64(),
  isAi: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const RegenTimer = __t.object("RegenTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type RegenTimer = __Infer<typeof RegenTimer>;

