// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Economic = __t.object("Economic", {
  territoryId: __t.i32(),
  ownerId: __t.i32(),
  capital: __t.i32(),
});
export type Economic = __Infer<typeof Economic>;

export const GameState = __t.object("GameState", {
  key: __t.string(),
  value: __t.string(),
});
export type GameState = __Infer<typeof GameState>;

export const Military = __t.object("Military", {
  territoryId: __t.i32(),
  ownerId: __t.i32(),
  troopCount: __t.i32(),
});
export type Military = __Infer<typeof Military>;

export const Player = __t.object("Player", {
  playerId: __t.i32(),
  playerName: __t.string(),
  color: __t.string(),
  actionPoints: __t.i32(),
  lastRegenAt: __t.i64(),
});
export type Player = __Infer<typeof Player>;

export const RegenTimer = __t.object("RegenTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type RegenTimer = __Infer<typeof RegenTimer>;

