// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as GetIntelProcedure from "../get_intel_procedure";

export type GetIntelArgs = __Infer<typeof GetIntelProcedure.params>;
export type GetIntelResult = __Infer<typeof GetIntelProcedure.returnType>;

